version: '3.4'

services:
  test:
    container_name: todoservice-test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/usr/app
    depends_on:
      - api
      - mongo
    env_file:
      - .env

volumes:
  mongodata: