version: '3.4'

services:
  api:
    image: hoyangtsai/todoservice
    container_name: todoservice
    restart: always
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin%2396:ys%40nEighTo@mongodb:27017
      - DATABASE_NAME=todo-db
    ports:
      - 9000:9000
    volumes:
      - .:/usr/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin#96
      - MONGO_INITDB_ROOT_PASSWORD=ys@nEighTo
      - MONGO_INITDB_DATABASE=todo-db
    ports:
      - 27017:27017

volumes:
  mongodata: