FROM node:14-alpine
ENV NODE_ENV=production

WORKDIR /usr/app

# Copy all source files
COPY ["package*.json", "tsconfig.json", "./"]

# Add dev deps
RUN npm ci

# Copy source code
COPY . .

RUN npm run build

EXPOSE 9000

CMD ["npm", "start"]